### ISSUE TITLE
Q to the "PrepareEnergyModel.CreateByMass" node

### ISSUE THREAD

**Issue by arkdanielnielsen** [tt-acm/EnergyAnalysisForDynamo#80]
First of all, this development is quite interesting!
I have been testing some of the example files. For that I have a couple of questions:
1) How can it be that there is no output for floors in the "PrepareEnergyModel.CreateByMass" node?
2) What is the function of the "PrepareEnergyModel.DrawAnalysisSurface" and "PrepareEnergyModel.DrawAnalysisZone" nodes?
Thanks,
daniel

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen @bhowes-tt I removed the outputs from createZones and added all the types to decompose zone so you can get it for a set of selected zones or all of them together.

![image](https://cloud.githubusercontent.com/assets/2915573/5650972/5df8387e-9671-11e4-9f2e-f12a04c282cf.png)

Will add more nodes so you can customize the properties too. Stay tuned!

**Comment by mostaphaRoudsari** [comment]
Since the only parameter that we can change for glazing, floor and interior walls is construction I created a single node as SetSurfaceConceptualConstruction which deals with the types internally and in case the construction type doesn't match the surface type it will give a warning to the user.

![image](https://cloud.githubusercontent.com/assets/2915573/5655196/321ccaf8-9699-11e4-9e0a-c89f30429d8e.png)

Once we have separate zones working, workflows like changing glazing type for windows facing north will be pretty easy to do!
